### ISSUE TITLE
GitHub Checklist

### ISSUE THREAD

**Issue by abitrolly** [yakshaveinc/tasks#25]
This should be automated.

* [ ] disable empty Projects tab in settings
* [ ] disable empty Wiki tab in settings

* [ ] check that LICENSE is detected and update if it is not
* [ ] add website (if any) to repository description
  * [ ] run https://validator.w3.org/checklink linkchecker for the URL
* [ ] add tags (if any) to repository description

https://github.com/rirror/rirror.github.io/blob/master/docs/GITHUB.md
