### ISSUE TITLE
Tracking DB schema changes

### ISSUE THREAD

**Issue by abitrolly** [yakshaveinc/tasks#80]
* [ ] use https://github.com/fschulze/sqlalchemy_schemadisplay/ to generate DB schema in .png
  * [ ] make sure the .png is reproducible
  * [ ] create .png diff and return non-zero code if changes are detected
  * [ ] release new version https://github.com/fschulze/sqlalchemy_schemadisplay/pull/30
    * [ ] test release process on tag
      * [ ] test release process by uploading to temp PyPI server
        * [ ] build PyPI server docker image
  * [ ] teach `build` to mention that packages are created in `dist/` subdir
    * [ ] get back color to `build` output (https://github.com/pypa/build/pull/494)
* [ ] wrap DB schema dump into GitHub action
